### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by TheYoxy** [marshalhayes/RemixRunDotNet#1]
Hi, 

I saw your repo which is exactly the use case I would apply for, but I have a question in my mind, have you already tried to deploy this stack in a production like environment ?

**Comment by marshalhayes** [comment]
I have not. 

If you follow best practices for both Remix and .NET, I bet you'd be fine. What are your concerns though?

**Comment by TheYoxy** [comment]
The main problem I see is how to keep SSR from RemixJS while hosting inside an .net core app, like you're not using any backend provided by the framework itself and I don't see any ways that could works unless you have 2 different backends running, one for the Remix app and another for your .net core api

**Comment by marshalhayes** [comment]
Good questions.

You'll need to run Remix and .NET as separate processes. In development, that happens simply by running the .NET app (and requests get proxied accordingly). In production however, you'd need to run Remix as one process and .NET as another. 

As long as you can access both apps over the network, it should work well.

**Comment by TheYoxy** [comment]
Yeah, that was my main concern, is it possible to have only one process for .net core app which would return the remix app. 

Thanks for your time!
